apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: incident-data-pvc
  namespace: incident-intelligence
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
